import { type Product, type Category } from './types'

export const categories: Category[] = [
  { id: '1', name: 'Цүнх & Уут', slug: 'bags', icon: '👜', productCount: 42 },
  { id: '2', name: 'Хувцас', slug: 'clothing', icon: '👗', productCount: 128 },
  { id: '3', name: 'Гутал', slug: 'shoes', icon: '👟', productCount: 64 },
  { id: '4', name: 'Гоо сайхан', slug: 'beauty', icon: '💄', productCount: 89 },
  { id: '5', name: 'Аксессуар', slug: 'accessories', icon: '⌚', productCount: 156 },
]

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Ягаан туслах цүнх',
    slug: 'pink-handbag',
    price: 89000,
    originalPrice: 120000,
    category: 'Цүнх & Уут',
    categorySlug: 'bags',
    badge: 'Хямдрал',
    images: ['https://picsum.photos/seed/p1/400/400'],
    description: 'Өдөр тутмын хэрэглээнд тохирсон гоёмсог ягаан цүнх.',
    inStock: true,
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: 'p2',
    name: 'Хар арьсан уут',
    slug: 'black-leather-tote',
    price: 145000,
    category: 'Цүнх & Уут',
    categorySlug: 'bags',
    badge: 'Hot',
    images: ['https://picsum.photos/seed/p2/400/400'],
    description: 'Өндөр чанарын арьсан материалтай хар өнгийн уут.',
    inStock: true,
    rating: 4.9,
    reviewCount: 89,
  },
  {
    id: 'p3',
    name: 'Зуны цагаан даашинз',
    slug: 'white-summer-dress',
    price: 65000,
    originalPrice: 85000,
    category: 'Хувцас',
    categorySlug: 'clothing',
    badge: 'New',
    images: ['https://picsum.photos/seed/p3/400/400'],
    description: 'Хөнгөн, агаар нэвтрүүлдэг зуны цагаан даашинз.',
    inStock: true,
    rating: 4.5,
    reviewCount: 210,
  },
  {
    id: 'p4',
    name: 'Бэлтгэлийн sneaker',
    slug: 'running-sneakers',
    price: 125000,
    category: 'Гутал',
    categorySlug: 'shoes',
    badge: 'Hot',
    images: ['https://picsum.photos/seed/p4/400/400'],
    description: 'Тав тухтай, хөнгөн бэлтгэлийн пүүз.',
    inStock: true,
    rating: 4.7,
    reviewCount: 56,
  },
  {
    id: 'p5',
    name: 'Арьс арчилгааны багц',
    slug: 'skincare-bundle',
    price: 189000,
    originalPrice: 240000,
    category: 'Гоо сайхан',
    categorySlug: 'beauty',
    badge: 'Хямдрал',
    images: ['https://picsum.photos/seed/p5/400/400'],
    description: 'Бүх төрлийн арьсанд тохирох иж бүрдэл.',
    inStock: true,
    rating: 4.9,
    reviewCount: 342,
  },
  {
    id: 'p6',
    name: 'Ухаалаг бугуйн цаг',
    slug: 'smart-watch-v2',
    price: 155000,
    category: 'Аксессуар',
    categorySlug: 'accessories',
    badge: 'New',
    images: ['https://picsum.photos/seed/p6/400/400'],
    description: 'Олон үйлдэлт ухаалаг бугуйн цаг.',
    inStock: true,
    rating: 4.6,
    reviewCount: 120,
  },
  {
    id: 'p7',
    name: 'Мөнгөн зүүлт сет',
    slug: 'silver-necklace-set',
    price: 45000,
    category: 'Аксессуар',
    categorySlug: 'accessories',
    badge: 'Хямдрал',
    images: ['https://picsum.photos/seed/p7/400/400'],
    description: '925 сорьцтой мөнгөн зүүлтний иж бүрдэл.',
    inStock: true,
    rating: 4.8,
    reviewCount: 78,
  },
  {
    id: 'p8',
    name: 'Богино ханцуйтай цамц',
    slug: 'cotton-tshirt',
    price: 35000,
    category: 'Хувцас',
    categorySlug: 'clothing',
    images: ['https://picsum.photos/seed/p8/400/400'],
    description: '100% даавуун материалтай богино ханцуйтай цамц.',
    inStock: true,
    rating: 4.4,
    reviewCount: 430,
  },
  {
    id: 'p9',
    name: 'Уруулын будаг (Матт)',
    slug: 'matte-lipstick',
    price: 25900,
    category: 'Гоо сайхан',
    categorySlug: 'beauty',
    images: ['https://picsum.photos/seed/p9/400/400'],
    description: 'Удаан тогтоцтой матт уруулын будаг.',
    inStock: true,
    rating: 4.7,
    reviewCount: 88,
  },
  {
    id: 'p10',
    name: 'Ажил хэрэгч гутал',
    slug: 'formal-shoes',
    price: 165000,
    originalPrice: 195000,
    category: 'Гутал',
    categorySlug: 'shoes',
    badge: 'Хямдрал',
    images: ['https://picsum.photos/seed/p10/400/400'],
    description: 'Классик загварын ажил хэрэгч арьсан гутал.',
    inStock: true,
    rating: 4.8,
    reviewCount: 52,
  },
  {
    id: 'p11',
    name: 'Жижиг үүргэвч',
    slug: 'mini-backpack',
    price: 75000,
    category: 'Цүнх & Уут',
    categorySlug: 'bags',
    images: ['https://picsum.photos/seed/p11/400/400'],
    description: 'Аялал болон өдөр тутамд тохиромжтой жижиг үүргэвч.',
    inStock: true,
    rating: 4.5,
    reviewCount: 34,
  },
  {
    id: 'p12',
    name: 'Жинсэн өмд',
    slug: 'blue-jeans',
    price: 85000,
    category: 'Хувцас',
    categorySlug: 'clothing',
    badge: 'Hot',
    images: ['https://picsum.photos/seed/p12/400/400'],
    description: 'Суналттай, тав тухтай цэнхэр жинсэн өмд.',
    inStock: true,
    rating: 4.6,
    reviewCount: 156,
  },
  {
    id: 'p13',
    name: 'Өвлийн куртка',
    slug: 'winter-jacket',
    price: 189000,
    originalPrice: 220000,
    category: 'Хувцас',
    categorySlug: 'clothing',
    badge: 'Хямдрал',
    images: ['https://picsum.photos/seed/p13/400/400'],
    description: 'Дулаахан, ус нэвтэрдэггүй өвлийн куртка.',
    inStock: true,
    rating: 4.9,
    reviewCount: 24,
  },
  {
    id: 'p14',
    name: 'Нарны шил',
    slug: 'oversized-sunglasses',
    price: 55000,
    category: 'Аксессуар',
    categorySlug: 'accessories',
    badge: 'New',
    images: ['https://picsum.photos/seed/p14/400/400'],
    description: 'UV хамгаалалттай загварлаг нарны шил.',
    inStock: true,
    rating: 4.7,
    reviewCount: 67,
  },
  {
    id: 'p15',
    name: 'Үнэртэй ус (50ml)',
    slug: 'signature-perfume',
    price: 135000,
    category: 'Гоо сайхан',
    categorySlug: 'beauty',
    badge: 'Hot',
    images: ['https://picsum.photos/seed/p15/400/400'],
    description: 'Зөөлөн, тансаг үнэртэй шилдэг ус.',
    inStock: true,
    rating: 4.9,
    reviewCount: 142,
  },
  {
    id: 'p16',
    name: 'Спортын цүнх',
    slug: 'gym-duffle-bag',
    price: 95000,
    category: 'Цүнх & Уут',
    categorySlug: 'bags',
    images: ['https://picsum.photos/seed/p16/400/400'],
    description: 'Заал болон бэлтгэлд зориулсан багтаамжтай цүнх.',
    inStock: true,
    rating: 4.6,
    reviewCount: 45,
  },
  {
    id: 'p17',
    name: 'Гэрийн тавчик',
    slug: 'fluffy-slippers',
    price: 29000,
    category: 'Гутал',
    categorySlug: 'shoes',
    images: ['https://picsum.photos/seed/p17/400/400'],
    description: 'Дулаахан, зөөлөн гэрийн тавчик.',
    inStock: true,
    rating: 4.8,
    reviewCount: 231,
  },
  {
    id: 'p18',
    name: 'Кашмер ороолт',
    slug: 'cashmere-scarf',
    price: 115000,
    category: 'Хувцас',
    categorySlug: 'clothing',
    badge: 'New',
    images: ['https://picsum.photos/seed/p18/400/400'],
    description: '100% кашмер материалтай зөөлөн ороолт.',
    inStock: true,
    rating: 4.9,
    reviewCount: 12,
  },
  {
    id: 'p19',
    name: 'Хөмсөгний харандаа',
    slug: 'eyebrow-pencil',
    price: 26900,
    category: 'Гоо сайхан',
    categorySlug: 'beauty',
    images: ['https://picsum.photos/seed/p19/400/400'],
    description: 'Байгалийн харагдах өнгө бүхий харандаа.',
    inStock: true,
    rating: 4.5,
    reviewCount: 94,
  },
  {
    id: 'p20',
    name: 'Арван хурууны бөгж',
    slug: 'stackable-rings',
    price: 39000,
    category: 'Аксессуар',
    categorySlug: 'accessories',
    images: ['https://picsum.photos/seed/p20/400/400'],
    description: 'Загварлаг, хослуулан зүүх боломжтой бөгжнүүд.',
    inStock: true,
    rating: 4.7,
    reviewCount: 116,
  },
]

export const brands = [
  { id: 'b1', name: 'Gobi' },
  { id: 'b2', name: 'Goyol' },
  { id: 'b3', name: 'Michel & Amazonka' },
  { id: 'b4', name: 'Lhamour' },
  { id: 'b5', name: 'Anar' },
  { id: 'b6', name: 'Tsetseg' },
  { id: 'b7', name: 'Belen' },
  { id: 'b8', name: 'Titem' },
]

export const heroSlides = [
  {
    id: 's1',
    title: 'Enola Shop-т тавтай морил',
    subtitle: 'Шинэ загвар. Шинэ мэдрэмж.',
    buttonText: 'Дэлгүүр харах →',
    buttonHref: '/shop',
    gradient: 'from-[#f3e8ff] to-[#e9d5ff]'
  },
  {
    id: 's2',
    title: 'Тусгай хямдрал -30%',
    subtitle: 'Сонгогдсон бараануудад онцгой хямдрал зарлалаа.',
    buttonText: 'Хямдралтай бараа →',
    buttonHref: '/shop?filter=sale',
    gradient: 'from-[#fdf4ff] to-[#fae8ff]'
  }
]
